### PR TITLE
Add default value of DEP_PATH

### PR DESCRIPTION
**Pull request by ChihweiLHBird**
Relevant issue: https://github.com/aufdenpunkt/python-safety-check/issues/2

@aufdenpunkt I think having a default value of the dependencies path is a good idea. What do you think? Can you help me to review this pull request? Thanks!

### CODE REVIEW

**Comment by aufdenpunkt** [comment]
Sounds great! Thanks for contributing!

**Comment by Mykhailo-Leskiv** [comment]
Line 15 should be REQS=${GITHUB_WORKSPACE}/${DEP_PATH} instead of REQS=${GITHUB_WORKSPACE}/DEP_PATH

**Comment by aufdenpunkt** [comment]
Ouch … absolutely …

**Comment by ChihweiLHBird** [comment]
> Line 15 should be REQS=${GITHUB_WORKSPACE}/${DEP_PATH} instead of REQS=${GITHUB_WORKSPACE}/DEP_PATH

@aufdenpunkt @Mykhailo-Leskiv Why it should be REQS=${GITHUB_WORKSPACE}/${DEP_PATH}? I think line 9-13 declares DEP_PATH and gives it a default value when the environmental variable not existing.

**Comment by ChihweiLHBird** [comment]
Oh, I got it, never mind. @aufdenpunkt @Mykhailo-Leskiv 
Sorry about the mistake

**Pull request merged**
